/*
 * config.h
 *
 *  Created on: Jul 26, 2024
 *      Author: Marcel
 */

#ifndef INC_CONFIG_H_
#define INC_CONFIG_H_

////////////////		INCLUDES

#include "tim.h"
#include "usart.h"
#include "gpio.h"
#include <stdbool.h>

////////////////		PINOUT SETTINGS

#define SEED_SENSOR_CHANNEL_1_PORT SENSOR_1_GPIO_Port
#define SEED_SENSOR_CHANNEL_1_PIN SENSOR_1_Pin
#define SEED_SENSOR_CHANNEL_2_PORT SENSOR_2_GPIO_Port
#define SEED_SENSOR_CHANNEL_2_PIN SENSOR_2_Pin
#define SEED_SENSOR_CHANNEL_3_PORT SENSOR_3_GPIO_Port
#define SEED_SENSOR_CHANNEL_3_PIN SENSOR_3_Pin

#define SEED_CHANNEL_1_PORT RELAY_1_GPIO_Port
#define SEED_CHANNEL_1_PIN RELAY_1_Pin
#define SEED_CHANNEL_2_PORT RELAY_2_GPIO_Port
#define SEED_CHANNEL_2_PIN RELAY_2_Pin
#define SEED_CHANNEL_3_PORT RELAY_3_GPIO_Port
#define SEED_CHANNEL_3_PIN RELAY_3_Pin
#define SEED_CHANNEL_4_PORT RELAY_4_GPIO_Port
#define SEED_CHANNEL_4_PIN RELAY_4_Pin
#define SEED_CHANNEL_5_PORT RELAY_5_GPIO_Port
#define SEED_CHANNEL_5_PIN RELAY_5_Pin
#define SEED_CHANNEL_6_PORT RELAY_6_GPIO_Port
#define SEED_CHANNEL_6_PIN RELAY_6_Pin

#define VIBRATE_MOTOR_FOR_PELLETED_SEEDS_PORT RELAY_7_GPIO_Port
#define VIBRATE_MOTOR_FOR_PELLETED_SEEDS_PIN RELAY_7_Pin
#define VIBRATE_MOTOR_FOR_CASUAL_SEEDS_PORT RELAY_8_GPIO_Port
#define VIBRATE_MOTOR_FOR_CASUAL_SEEDS_PIN RELAY_8_Pin

#define PELLETED_SEEDS_STEPPER_EN_PORT STEPPER1_EN_GPIO_Port
#define PELLETED_SEEDS_STEPPER_EN_PIN STEPPER1_EN_Pin
#define PELLETED_SEEDS_STEPPER_DIR_PORT STEPPER1_DIR_GPIO_Port
#define PELLETED_SEEDS_STEPPER_DIR_PIN STEPPER1_DIR_Pin

#define DROPPER_STEPPER_EN_PORT STEPPER2_EN_GPIO_Port
#define DROPPER_STEPPER_EN_PIN STEPPER2_EN_Pin
#define DROPPER_STEPPER_DIR_PORT STEPPER2_DIR_GPIO_Port
#define DROPPER_STEPPER_DIR_PIN STEPPER2_DIR_Pin


////////////////		HARDWARE SETTINGS

#define DRUM_STEPPER_MICROSTEPPING 32
#define DROPPER_STEPPER_MICROSTEPPING 32
#define DEFAULT_ANGLE_PER_STEP 1.8


////////////////		MECHANICAL SETTINGS

#define DROPPER_STEPPER_PULLEY_DIAMETER_MM 10
#define NUMBER_OF_CHANNELS 6
#define NUMBER_OF_VIBRATE_MOTORS 2


////////////////		SOWING SETTINGS

#define SHAKING_TIME_AFTER_DROPPER_REFILL_MS 15000
#define SOWING_TIME_FOR_CASUAL_SEEDS_MS 500
#define SOWING_PELLETED_SEED_MAX_TIMEOUT_MS 3000


////////////////		OTHER SETTINGS

#define PI 3.14

#endif /* INC_CONFIG_H_ */
