/*
 * config.h
 *
 *  Created on: Jul 26, 2024
 *      Author: Marcel
 */

#ifndef INC_CONFIG_H_
#define INC_CONFIG_H_

////////////////		INCLUDES

#include "tim.h"
#include "usart.h"
#include "gpio.h"
#include <stdbool.h>

////////////////		PINOUT SETTINGS

#define SEED_SENSOR_CHANNEL_1_PORT 		SENSOR_1_GPIO_Port
#define SEED_SENSOR_CHANNEL_1_PIN 		SENSOR_1_Pin
#define SEED_SENSOR_CHANNEL_2_PORT 		SENSOR_2_GPIO_Port
#define SEED_SENSOR_CHANNEL_2_PIN 		SENSOR_2_Pin
#define SEED_SENSOR_CHANNEL_3_PORT 		SENSOR_3_GPIO_Port
#define SEED_SENSOR_CHANNEL_3_PIN 		SENSOR_3_Pin
#define DROPPER_HOMING_SENSOR_PORT 		SENSOR_4_GPIO_Port
#define DROPPER_HOMING_SENSOR_PIN 		SENSOR_4_Pin
#define EMPTY_MULTIPLAT_PUSHER_MIN_ENDSTOP_PORT	SENSOR_8_GPIO_Port
#define EMPTY_MULTIPLAT_PUSHER_MIN_ENDSTOP_PIN	SENSOR_8_Pin
#define EMPTY_MULTIPLAT_PUSHER_MAX_ENDSTOP_PORT	SENSOR_7_GPIO_Port
#define EMPTY_MULTIPLAT_PUSHER_MAX_ENDSTOP_PIN	SENSOR_7_Pin

//do walidacji
#define FULL_MULTIPLAT_PUSHER_MIN_ENDSTOP_PORT	SENSOR_9_GPIO_Port
#define FULL_MULTIPLAT_PUSHER_MIN_ENDSTOP_PIN	SENSOR_9_Pin
#define FULL_MULTIPLAT_PUSHER_MAX_ENDSTOP_PORT	SENSOR_10_GPIO_Port
#define FULL_MULTIPLAT_PUSHER_MAX_ENDSTOP_PIN	SENSOR_10_Pin

#define SEED_CHANNEL_1_PORT 			RELAY_1_GPIO_Port
#define SEED_CHANNEL_1_PIN 				RELAY_1_Pin
#define SEED_CHANNEL_2_PORT 			RELAY_2_GPIO_Port
#define SEED_CHANNEL_2_PIN 				RELAY_2_Pin
#define SEED_CHANNEL_3_PORT 			RELAY_3_GPIO_Port
#define SEED_CHANNEL_3_PIN 				RELAY_3_Pin
#define SEED_CHANNEL_4_PORT 			RELAY_4_GPIO_Port
#define SEED_CHANNEL_4_PIN 				RELAY_4_Pin
#define SEED_CHANNEL_5_PORT 			RELAY_5_GPIO_Port
#define SEED_CHANNEL_5_PIN 				RELAY_5_Pin
#define SEED_CHANNEL_6_PORT 			RELAY_6_GPIO_Port
#define SEED_CHANNEL_6_PIN 				RELAY_6_Pin
#define UPPER_PUSHER_MOVE_FORWARD_PORT	RELAY_9_GPIO_Port
#define UPPER_PUSHER_MOVE_FORWARD_Pin	RELAY_9_Pin
#define UPPER_PUSHER_MOVE_BACKWARD_PORT	RELAY_10_GPIO_Port
#define UPPER_PUSHER_MOVE_BACKWARD_Pin	RELAY_10_Pin
#define LOWER_PUSHER_MOVE_FORWARD_PORT	RELAY_15_GPIO_Port
#define LOWER_PUSHER_MOVE_FORWARD_Pin	RELAY_15_Pin
#define LOWER_PUSHER_MOVE_BACKWARD_PORT	RELAY_16_GPIO_Port
#define LOWER_PUSHER_MOVE_BACKWARD_Pin	RELAY_16_Pin

#define VIBRATE_MOTOR_FOR_CASUAL_SEEDS_PORT 	RELAY_7_GPIO_Port
#define VIBRATE_MOTOR_FOR_CASUAL_SEEDS_PIN 		RELAY_7_Pin

#define PELLETED_SEEDS_STEPPER_EN_PORT 			STEPPER1_EN_GPIO_Port
#define PELLETED_SEEDS_STEPPER_EN_PIN 			STEPPER1_EN_Pin
#define PELLETED_SEEDS_STEPPER_DIR_PORT 		STEPPER1_DIR_GPIO_Port
#define PELLETED_SEEDS_STEPPER_DIR_PIN 			STEPPER1_DIR_Pin

#define DROPPER_STEPPER_EN_PORT 	STEPPER2_EN_GPIO_Port
#define DROPPER_STEPPER_EN_PIN 		STEPPER2_EN_Pin
#define DROPPER_STEPPER_DIR_PORT 	STEPPER2_DIR_GPIO_Port
#define DROPPER_STEPPER_DIR_PIN 	STEPPER2_DIR_Pin


////////////////		HARDWARE SETTINGS

#define DRUM_STEPPER_MICROSTEPPING 			32
#define DROPPER_STEPPER_MICROSTEPPING 		32
#define DEFAULT_ANGLE_PER_STEP 				1.8


////////////////		MECHANICAL SETTINGS

#define DROPPER_STEPPER_PULLEY_DIAMETER_MM 	15
#define NUMBER_OF_CHANNELS 					6
#define NUMBER_OF_VIBRATE_MOTORS 			2

#define PUSHING_EMPTY_MULTIPLAT_MAX_TIMEOUT_MS	30000
#define HOMING_TIMEOUT							10000
#define SELFTEST_SINGLETEST_TIMEOUT_MS			5000

#define HOMING_LOWER_PUSHER_MAX_TIMEOUT_MS		30000
#define HOMING_UPPER_PUSHER_MAX_TIMEOUT_MS		30000

////////////////		SOWING SETTINGS

#define SHAKING_TIME_AFTER_REFILL_MS 		3000
#define SOWING_TIME_FOR_CASUAL_SEEDS_MS 	500
#define SOWING_PELLETED_SEED_MAX_TIMEOUT_MS 15000
#define MAX_SOWS_AT_ONCE 					10

#define DISTANCE_BETWEEN_CENTERS_OF_TWO_POTS_MM 	40
#define DISTANCE_TO_THE_FIRST_POT_MM 				300

#define FIRST_CHANNEL_OFFSET_MM 	1
#define SECOND_CHANNEL_OFFSET_MM 	1
#define THIRD_CHANNEL_OFFSET_MM 	1
#define FOURTH_CHANNEL_OFFSET_MM 	1
#define FIFTH_CHANNEL_OFFSET_MM 	1
#define SIXTH_CHANNEL_OFFSET_MM 	1

#define NUMBER_OF_SOWING_TRIALS		3


////////////////		OTHER SETTINGS

#define PI 	3.14

#endif /* INC_CONFIG_H_ */
